/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


DROP DATABASE IF EXISTS `heroku_ca53e8cabd3c7ad`;
CREATE DATABASE IF NOT EXISTS `heroku_ca53e8cabd3c7ad`;

USE `heroku_ca53e8cabd3c7ad`;


DROP TABLE IF EXISTS `comunicaPerda`;

CREATE TABLE comunicaPerda(
	id INT AUTO_INCREMENT,
	nome VARCHAR(40),
	email VARCHAR(255),
	cpf VARCHAR(11),
	coordenada POINT,
	tipo VARCHAR(20),
	data DATE,
	evento VARCHAR(20),
	PRIMARY KEY(id)
);